# Generated by Django 4.2.5 on 2024-02-15 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_complex_category_complex_company_complex_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='complex',
            name='number_room',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='payment',
            field=models.IntegerField(choices=[(1, 'caw'), (2, 'cart'), (3, 'credit')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='price',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='square',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.stata'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complex',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='House',
        ),
    ]
