# Generated by Django 4.2.5 on 2024-02-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_viewed_complex_number_room_complex_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='payment_date',
            field=models.CharField(max_length=255),
        ),
    ]
