# Generated by Django 4.2.5 on 2024-02-15 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_compleximage_environmentimg_featureimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='viewed',
            new_name='announcement',
        ),
    ]
