# Generated by Django 4.2.5 on 2024-02-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_viewed_company_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyComplexIMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='CompanyComplexIMG')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='complex_img',
            field=models.ManyToManyField(to='main.companycompleximg'),
        ),
    ]
