# Generated by Django 4.2.5 on 2024-02-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_companycompleximg_company_complex_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='about',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='complex',
            name='number_room',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4+')]),
        ),
    ]
