# Generated by Django 4.2.5 on 2024-02-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_complex_about_alter_complex_number_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complex',
            name='payment',
        ),
        migrations.AlterField(
            model_name='complex',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
